/** 4T member account: only signed-in customers can see orders, loyalty and submit per-order service reviews. */
import { useAuth } from "@/_core/hooks/useAuth";
import { SupportChat } from "@/components/SupportChat";
import { StorefrontHeader } from "@/components/StorefrontHeader";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { Award, CalendarClock, ChevronRight, CircleHelp, Clock3, Loader2, LogOut, PackagePlus, Sparkles, Star } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";

const labels: Record<string, string> = { requested: "Đã tiếp nhận", confirmed: "Đã xác nhận", pickup: "Đang lấy đồ", washing: "Đang giặt", drying: "Đang sấy", ready: "Sẵn sàng giao trả", completed: "Hoàn tất", cancelled: "Đã hủy" };

export default function AccountPage() {
  const { user, loading, isAuthenticated, logout } = useAuth();
  const orders = trpc.account.orders.useQuery(undefined, { enabled: isAuthenticated });
  const loyalty = trpc.account.loyalty.useQuery(undefined, { enabled: isAuthenticated });
  const utils = trpc.useUtils();
  const [review, setReview] = useState<{ orderId: number; rating: number; comment: string } | null>(null);
  const submitReview = trpc.account.review.useMutation({ onSuccess: () => { setReview(null); utils.account.orders.invalidate(); } });
  if (loading) return <div className="min-h-screen bg-[#F7FAFF]"><StorefrontHeader /><div className="mx-auto max-w-6xl px-4 py-16 text-sm font-bold text-[#61718A]">Đang mở tài khoản 4T…</div></div>;
  if (!isAuthenticated) return <div className="min-h-screen bg-[#F7FAFF]"><StorefrontHeader /><main className="mx-auto max-w-3xl px-4 py-16 sm:px-7"><section className="rounded-[32px] bg-[#092C5C] p-8 text-white sm:p-12"><Sparkles className="h-7 w-7 text-[#8FD7FF]" /><p className="eyebrow mt-7 text-[#AEE2FF]">TÀI KHOẢN 4T</p><h1 className="mt-3 font-display text-5xl font-semibold leading-none">Theo dõi từng mẻ giặt. Tích từng điểm 4T.</h1><p className="mt-6 max-w-xl text-base leading-7 text-[#D6E8FF]">Đăng nhập để xem tiến độ đơn, lịch sử dịch vụ, số điểm tích lũy và gửi đánh giá sau mỗi đơn hoàn tất.</p><div className="mt-8 flex flex-wrap gap-3"><Button onClick={startLogin} className="rounded-full bg-[#E7425A] px-6 font-extrabold hover:bg-[#C92F47]">Đăng nhập / tạo tài khoản</Button><Link href="/dat-don"><Button variant="outline" className="rounded-full border-white/30 bg-white/5 font-extrabold text-white hover:bg-white/12 hover:text-white">Tôi muốn đặt đơn vãng lai</Button></Link></div></section><p className="mt-5 rounded-2xl border border-[#092C5C]/8 bg-white p-5 text-sm leading-6 text-[#61718A]">Bạn vẫn có thể tạo đơn khi chưa đăng nhập. Tuy nhiên, để bảo vệ thông tin khách hàng, đơn vãng lai không hiện tiến độ hoặc được tính điểm trong website.</p></main><SupportChat /></div>;
  return <div className="min-h-screen bg-[#F7FAFF]"><StorefrontHeader /><main className="mx-auto max-w-7xl px-4 py-10 sm:px-7"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">TÀI KHOẢN 4T</p><h1 className="mt-3 font-display text-5xl font-semibold tracking-[-.04em] text-[#092C5C]">Chào {user?.name?.split(" ")[0] || "bạn"}.</h1><p className="mt-3 text-sm text-[#61718A]">Đơn hàng, tiến độ và điểm tích lũy của bạn được hiển thị tại đây.</p></div><div className="flex gap-2"><Link href="/dat-don"><Button className="rounded-full bg-[#E7425A] font-extrabold hover:bg-[#C92F47]"><PackagePlus className="mr-2 h-4 w-4" />Đặt đơn mới</Button></Link><Button onClick={logout} variant="outline" className="rounded-full border-[#092C5C]/15 bg-white text-[#092C5C]"><LogOut className="h-4 w-4" /></Button></div></div>
    <section className="mt-8 grid gap-4 md:grid-cols-[1.25fr_.75fr]"><div className="rounded-[28px] bg-[#092C5C] p-7 text-white sm:p-8"><div className="flex items-start justify-between"><div><p className="text-[10px] font-extrabold tracking-[.16em] text-[#AEE2FF]">ĐIỂM 4T CỦA BẠN</p><p className="mt-4 text-5xl font-extrabold tracking-[-.05em]">{loyalty.data?.currentPoints ?? 0}<span className="ml-2 text-base font-bold text-[#BFD8F2]">điểm</span></p></div><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-white/10"><Award className="h-6 w-6 text-[#8FD7FF]" /></span></div><p className="mt-6 max-w-md text-sm leading-6 text-[#D6E8FF]">Mỗi 10.000đ giá trị đơn hoàn tất được tích 1 điểm. Điểm chỉ được ghi nhận cho đơn được tạo khi đã đăng nhập.</p></div><div className="rounded-[28px] border border-[#092C5C]/9 bg-white p-7"><CalendarClock className="h-5 w-5 text-[#1677C7]" /><p className="mt-6 text-2xl font-extrabold text-[#092C5C]">{loyalty.data?.totalEarned ?? 0}</p><p className="mt-1 text-sm text-[#61718A]">Tổng điểm đã tích lũy</p><p className="mt-6 border-t border-[#092C5C]/8 pt-4 text-xs leading-5 text-[#7B89A1]">Ưu đãi quy đổi sẽ được 4T cập nhật trong các chương trình thành viên.</p></div></section>
    <section className="mt-10"><div className="flex items-center justify-between"><div><p className="eyebrow">ĐƠN HÀNG CỦA BẠN</p><h2 className="mt-3 font-display text-4xl font-semibold text-[#092C5C]">Tiến độ xử lý</h2></div><p className="text-sm font-bold text-[#61718A]">{orders.data?.length ?? 0} đơn</p></div>{orders.isLoading ? <div className="mt-6 flex items-center gap-3 rounded-2xl bg-white p-6 text-sm text-[#61718A]"><Loader2 className="h-4 w-4 animate-spin" />Đang tải đơn hàng…</div> : (orders.data?.length ? <div className="mt-6 space-y-4">{orders.data.map(order => <article key={order.id} className="overflow-hidden rounded-[24px] border border-[#092C5C]/9 bg-white"><div className="flex flex-col gap-5 p-5 sm:flex-row sm:items-center sm:justify-between sm:p-6"><div><p className="text-[10px] font-extrabold tracking-[.12em] text-[#75859D]">{order.publicCode}</p><h3 className="mt-1 text-base font-extrabold text-[#092C5C]">{order.serviceTier === "express" ? "Giặt sấy nhanh" : "Giặt sấy tiêu chuẩn"} · {order.estimatedKg} kg</h3><p className="mt-1 text-sm text-[#61718A]">{new Date(order.createdAt).toLocaleString("vi-VN")} · {order.estimatedTotalVnd.toLocaleString("vi-VN")}đ</p></div><span className={`status-pill status-${order.status}`}>{labels[order.status]}</span></div><div className="border-t border-[#092C5C]/8 bg-[#FAFCFF] p-5"><div className="flex items-center gap-2 overflow-x-auto pb-1">{order.history.map((step, i) => <div key={step.id} className="flex shrink-0 items-center gap-2"><span className={`h-2.5 w-2.5 rounded-full ${step.status === order.status ? "bg-[#E7425A]" : "bg-[#9DD2F0]"}`} /><span className="text-xs font-bold text-[#53657E]">{labels[step.status]}</span>{i < order.history.length - 1 && <ChevronRight className="h-3.5 w-3.5 text-[#B6C2D5]" />}</div>)}</div>{order.status === "completed" && !order.review && <button onClick={() => setReview({ orderId: order.id, rating: 5, comment: "" })} className="mt-4 text-sm font-extrabold text-[#E7425A] hover:underline">Đánh giá chất lượng phục vụ</button>}{order.review && <p className="mt-4 inline-flex items-center gap-1 text-sm font-bold text-[#D98B00]"><Star className="h-4 w-4 fill-current" /> {order.review.rating}/5 · Cảm ơn bạn đã đánh giá</p>}</div></article>)}</div> : <div className="mt-6 rounded-[24px] border border-dashed border-[#092C5C]/18 bg-white p-10 text-center"><CircleHelp className="mx-auto h-6 w-6 text-[#8AA0BD]" /><h3 className="mt-4 font-extrabold text-[#092C5C]">Chưa có đơn nào trong tài khoản</h3><p className="mt-2 text-sm text-[#61718A]">Đặt đơn ngay khi đang đăng nhập để theo dõi tiến độ và nhận điểm.</p><Link href="/dat-don"><Button className="mt-5 rounded-full bg-[#092C5C] font-extrabold hover:bg-[#123D75]">Tạo đơn đầu tiên</Button></Link></div>)}</section>
    {review && <div className="fixed inset-0 z-50 flex items-end bg-[#092C5C]/35 p-4 sm:items-center sm:justify-center"><section className="w-full max-w-md rounded-[28px] bg-white p-6 shadow-2xl"><p className="eyebrow">ĐÁNH GIÁ ĐƠN HÀNG</p><h2 className="mt-3 text-2xl font-extrabold text-[#092C5C]">4T đã phục vụ bạn thế nào?</h2><div className="mt-5 flex gap-2">{[1, 2, 3, 4, 5].map(n => <button key={n} onClick={() => setReview({ ...review, rating: n })} className={`rounded-full p-2 ${n <= review.rating ? "text-[#F0A213]" : "text-[#C6D1E0]"}`}><Star className="h-7 w-7 fill-current" /></button>)}</div><Textarea value={review.comment} onChange={e => setReview({ ...review, comment: e.target.value })} className="mt-5" placeholder="Góp ý của bạn giúp 4T tốt hơn (tùy chọn)" /><div className="mt-5 flex justify-end gap-2"><Button variant="ghost" onClick={() => setReview(null)}>Hủy</Button><Button disabled={submitReview.isPending} onClick={() => submitReview.mutate(review)} className="rounded-full bg-[#E7425A] font-extrabold hover:bg-[#C92F47]">{submitReview.isPending ? "Đang gửi" : "Gửi đánh giá"}</Button></div></section></div>}
  </main><SupportChat /></div>;
}
