/** 4T admin workspace: owner-only order operations, customer list, feedback and support conversations. */
import { useAuth } from "@/_core/hooks/useAuth";
import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { BarChart3, Clock3, MessageCircleMore, PackageCheck, Star, UsersRound } from "lucide-react";
import { useMemo, useState } from "react";

const labels: Record<string, string> = { requested: "Đã tiếp nhận", confirmed: "Đã xác nhận", pickup: "Đang lấy đồ", washing: "Đang giặt", drying: "Đang sấy", ready: "Sẵn sàng giao trả", completed: "Hoàn tất", cancelled: "Đã hủy" };
const statusOptions = ["requested", "confirmed", "pickup", "washing", "drying", "ready", "completed", "cancelled"] as const;

export default function AdminPage() {
  const { user, loading } = useAuth();
  return <DashboardLayout>{loading ? null : user?.role === "admin" ? <AdminWorkspace /> : <div className="p-8"><p className="eyebrow">KHU VỰC HẠN CHẾ</p><h1 className="mt-3 text-3xl font-extrabold text-[#092C5C]">Bạn chưa có quyền quản trị 4T.</h1><p className="mt-3 text-sm text-[#61718A]">Chỉ tài khoản chủ sở hữu dự án được truy cập bảng điều hành.</p></div>}</DashboardLayout>;
}

function AdminWorkspace() {
  const metrics = trpc.admin.metrics.useQuery();
  const orders = trpc.admin.orders.useQuery();
  const support = trpc.admin.support.useQuery();
  const utils = trpc.useUtils();
  const [selectedThread, setSelectedThread] = useState("");
  const [reply, setReply] = useState("");
  const update = trpc.admin.updateOrder.useMutation({ onSuccess: () => { utils.admin.orders.invalidate(); utils.admin.metrics.invalidate(); } });
  const replySupport = trpc.admin.replySupport.useMutation({ onSuccess: () => { setReply(""); utils.admin.support.invalidate(); } });
  const threads = useMemo(() => Object.values((support.data ?? []).reduce<Record<string, { threadKey: string; body: string; visitorName: string | null; contact: string | null; createdAt: Date }>>((all, message) => { if (!all[message.threadKey] || all[message.threadKey].createdAt < message.createdAt) all[message.threadKey] = message; return all; }, {})).sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime()), [support.data]);
  const messages = (support.data ?? []).filter(item => item.threadKey === selectedThread);
  const customers = useMemo(() => Object.values((orders.data ?? []).reduce<Record<string, { name: string; phone: string; orderCount: number; total: number }>>((all, order) => { const key = order.customerPhone; if (!all[key]) all[key] = { name: order.customerName, phone: order.customerPhone, orderCount: 0, total: 0 }; all[key].orderCount += 1; all[key].total += order.estimatedTotalVnd; return all; }, {})).sort((a, b) => b.total - a.total), [orders.data]);
  const reviews = useMemo(() => (orders.data ?? []).flatMap(order => order.review ? [{ ...order.review, publicCode: order.publicCode, customerName: order.customerName }] : []), [orders.data]);

  return <div className="mx-auto max-w-7xl space-y-8 p-2 sm:p-5">
    <div><p className="eyebrow">BẢNG ĐIỀU HÀNH 4T</p><h1 className="mt-2 text-3xl font-extrabold tracking-tight text-[#092C5C]">Vận hành hôm nay</h1></div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><AdminMetric icon={<UsersRound />} value={String(metrics.data?.visits ?? 0)} label="Lượt truy cập" /><AdminMetric icon={<PackageCheck />} value={String(metrics.data?.orders ?? 0)} label="Tổng đơn web" /><AdminMetric icon={<Clock3 />} value={String(metrics.data?.pending ?? 0)} label="Đơn chờ xác nhận" /><AdminMetric icon={<Star />} value={(metrics.data?.averageRating ?? 0).toFixed(1)} label="Đánh giá trung bình" /></div>
    <section className="rounded-2xl border border-[#092C5C]/10 bg-white"><div className="flex items-center justify-between border-b border-[#092C5C]/8 p-5"><div><p className="text-base font-extrabold text-[#092C5C]">Đơn hàng mới nhất</p><p className="mt-1 text-sm text-[#6D7F9B]">Đổi trạng thái để cập nhật tiến độ và tự động tích điểm cho đơn thành viên khi hoàn tất.</p></div><BarChart3 className="h-5 w-5 text-[#1677C7]" /></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead className="bg-[#F6F9FF] text-[10px] font-extrabold uppercase tracking-[.1em] text-[#71809A]"><tr><th className="px-5 py-3">Mã đơn</th><th className="px-5 py-3">Khách hàng</th><th className="px-5 py-3">Dịch vụ</th><th className="px-5 py-3">Thanh toán</th><th className="px-5 py-3">Trạng thái</th></tr></thead><tbody>{orders.data?.map(order => <tr key={order.id} className="border-t border-[#092C5C]/7"><td className="px-5 py-4 text-xs font-extrabold text-[#092C5C]">{order.publicCode}<span className="mt-1 block font-normal text-[#71809A]">{new Date(order.createdAt).toLocaleString("vi-VN")}</span></td><td className="px-5 py-4 text-sm"><b className="block text-[#334866]">{order.customerName}</b><span className="text-[#71809A]">{order.customerPhone}</span></td><td className="px-5 py-4 text-sm text-[#61718A]">{order.estimatedKg} kg · {order.serviceTier === "express" ? "Nhanh" : "Tiêu chuẩn"}<b className="mt-1 block text-[#092C5C]">{order.estimatedTotalVnd.toLocaleString("vi-VN")}đ</b></td><td className="px-5 py-4 text-sm text-[#61718A]">{order.paymentMethod === "cash" ? "Tiền mặt" : order.paymentMethod === "bank_transfer" ? "App ngân hàng" : "Ví điện tử"}<span className="mt-1 block text-xs">{order.paymentStatus}</span></td><td className="px-5 py-4"><select value={order.status} onChange={e => update.mutate({ orderId: order.id, status: e.target.value as typeof statusOptions[number], note: labels[e.target.value] })} className="rounded-lg border border-[#092C5C]/12 bg-white px-3 py-2 text-xs font-bold text-[#334866]">{statusOptions.map(value => <option key={value} value={value}>{labels[value]}</option>)}</select></td></tr>)}{!orders.data?.length && <tr><td colSpan={5} className="px-5 py-12 text-center text-sm text-[#71809A]">Chưa có đơn hàng nào từ website.</td></tr>}</tbody></table></div></section>
    <section className="grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border border-[#092C5C]/10 bg-white p-5"><p className="font-extrabold text-[#092C5C]">Khách hàng từ website</p><div className="mt-4 divide-y divide-[#092C5C]/8">{customers.slice(0, 6).map(customer => <div key={customer.phone} className="flex items-center justify-between py-3"><div><p className="text-sm font-bold text-[#334866]">{customer.name}</p><p className="mt-1 text-xs text-[#71809A]">{customer.phone} · {customer.orderCount} đơn</p></div><p className="text-xs font-extrabold text-[#092C5C]">{customer.total.toLocaleString("vi-VN")}đ</p></div>)}{!customers.length && <p className="py-8 text-center text-sm text-[#71809A]">Khách web sẽ hiện sau khi có đơn đầu tiên.</p>}</div></div><div className="rounded-2xl border border-[#092C5C]/10 bg-white p-5"><p className="font-extrabold text-[#092C5C]">Đánh giá theo đơn</p><div className="mt-4 space-y-3">{reviews.slice(0, 5).map(review => <div key={review.id} className="rounded-xl bg-[#F8FBFF] p-3"><p className="flex items-center gap-1 text-sm font-extrabold text-[#D98B00]"><Star className="h-4 w-4 fill-current" /> {review.rating}/5 <span className="ml-1 text-xs font-medium text-[#71809A]">· {review.publicCode}</span></p><p className="mt-2 text-xs leading-5 text-[#61718A]">{review.comment || "Khách hàng không để lại bình luận."}</p></div>)}{!reviews.length && <p className="py-8 text-center text-sm text-[#71809A]">Đánh giá từ đơn hoàn tất sẽ hiển thị ở đây.</p>}</div></div></section>
    <section className="grid gap-5 lg:grid-cols-[.75fr_1.25fr]"><div className="rounded-2xl border border-[#092C5C]/10 bg-white p-5"><div className="flex items-center justify-between"><p className="font-extrabold text-[#092C5C]">Tin nhắn cần hỗ trợ</p><MessageCircleMore className="h-5 w-5 text-[#1677C7]" /></div><div className="mt-4 divide-y divide-[#092C5C]/8">{threads.map(thread => <button key={thread.threadKey} onClick={() => setSelectedThread(thread.threadKey)} className={`w-full p-3 text-left ${selectedThread === thread.threadKey ? "bg-[#E8F5FF]" : "hover:bg-[#F8FBFF]"}`}><p className="text-sm font-bold text-[#092C5C]">{thread.visitorName || "Khách vãng lai"}</p><p className="mt-1 truncate text-xs text-[#6D7F9B]">{thread.body}</p></button>)}{!threads.length && <p className="py-8 text-center text-sm text-[#71809A]">Chưa có tin nhắn.</p>}</div></div><div className="rounded-2xl border border-[#092C5C]/10 bg-white p-5"><p className="font-extrabold text-[#092C5C]">{selectedThread ? "Hội thoại khách hàng" : "Chọn một hội thoại"}</p><div className="mt-4 min-h-[180px] space-y-3 rounded-xl bg-[#F6F9FF] p-4">{messages.map(message => <div key={message.id} className={`flex ${message.sender === "staff" ? "justify-end" : "justify-start"}`}><p className={`max-w-[80%] rounded-2xl px-3 py-2 text-sm ${message.sender === "staff" ? "bg-[#092C5C] text-white" : "bg-white text-[#334866]"}`}>{message.body}</p></div>)}</div><div className="mt-3 flex gap-2"><Input value={reply} onChange={e => setReply(e.target.value)} disabled={!selectedThread} placeholder="Nhập phản hồi của 4T…" /><Button disabled={!selectedThread || !reply.trim() || replySupport.isPending} onClick={() => replySupport.mutate({ threadKey: selectedThread, body: reply })} className="bg-[#E7425A] font-extrabold hover:bg-[#C92F47]">Gửi</Button></div></div></section>
  </div>;
}

function AdminMetric({ icon, value, label }: { icon: React.ReactNode; value: string; label: string }) { return <article className="rounded-2xl border border-[#092C5C]/9 bg-white p-5"><span className="text-[#1677C7]">{icon}</span><p className="mt-5 text-3xl font-extrabold text-[#092C5C]">{value}</p><p className="mt-1 text-xs font-bold text-[#71809A]">{label}</p></article>; }
